### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by gachet** [IoTopenTech/myIoTopenTech#7]
Hola Juan Félix

.\HTU21D.cpp:108:10: error: no member named 'free' in 'mbed::I2C'
i2c_.free();

No existe este método en el API I2C de MBED
Alguna sugerencia ?

Un saludp
DG

**Comment by jfmateos** [comment]
Hola @gachet 
Tienes que añadir esto
![imagen](https://user-images.githubusercontent.com/29097198/189524928-5a303b1d-bb65-410f-ac80-064ff1293cfb.png)

No recuero si llegamos a verlo en las sesiones que dedicamos a mbed
![imagen](https://user-images.githubusercontent.com/29097198/189524983-81830c80-f6db-4c14-b56c-75e9ed640f44.png)

**Comment by gachet** [comment]
Gracias JF

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: ***@***.***>
Enviado: domingo, 11 de septiembre de 2022 13:28
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [IoTopenTech/myIoTopenTech] compile error (Issue #7)


Hola @gachet<https://github.com/gachet>
Tienes que añadir esto
[imagen]<https://user-images.githubusercontent.com/29097198/189524928-5a303b1d-bb65-410f-ac80-064ff1293cfb.png>
